#=============================================================================#
#                                                                             #
#                           Elements - Worldwide                              #
#                                                                             #
#=============================================================================#

COLOURS = [
    '#636EFA', '#EF553B', '#00CC96', '#AB63FA', '#FFA15A', '#19D3F3',
    '#FF6692', '#B6E880', '#FF97FF', '#FECB52', '#636EFA', '#EF553B',
    '#00CC96', '#AB63FA', '#FFA15A', '#19D3F3', '#FF6692', '#B6E880',
    '#FF97FF', '#FECB52', '#636EFA', '#EF553B', '#00CC96', '#AB63FA',
    '#FFA15A', '#19D3F3', '#FF6692', '#B6E880', '#FF97FF', '#FECB52',
    '#636EFA', '#EF553B', '#00CC96', '#AB63FA', '#FFA15A', '#19D3F3',
    '#FF6692', '#B6E880', '#FF97FF', '#FECB52', '#636EFA', '#EF553B',
    '#00CC96', '#AB63FA', '#FFA15A', '#19D3F3', '#FF6692', '#B6E880',
    '#FF97FF', '#FECB52', '#636EFA', '#EF553B', '#00CC96', '#AB63FA',
    '#FFA15A', '#19D3F3', '#FF6692', '#B6E880', '#FF97FF', '#FECB52',
    '#636EFA', '#EF553B', '#00CC96', '#AB63FA', '#FFA15A', '#19D3F3',
    '#FF6692', '#B6E880', '#FF97FF', '#FECB52', '#636EFA', '#EF553B',
    '#00CC96', '#AB63FA', '#FFA15A', '#19D3F3', '#FF6692', '#B6E880',
    '#FF97FF', '#FECB52', '#636EFA', '#EF553B', '#00CC96', '#AB63FA',
    '#FFA15A', '#19D3F3', '#FF6692', '#B6E880', '#FF97FF', '#FECB52',
    '#636EFA', '#EF553B', '#00CC96', '#AB63FA', '#FFA15A', '#19D3F3',
    '#FF6692', '#B6E880', '#FF97FF', '#FECB52', '#636EFA', '#EF553B',
    '#00CC96', '#AB63FA', '#FFA15A', '#19D3F3', '#FF6692', '#B6E880',
    '#FF97FF', '#FECB52', '#636EFA', '#EF553B', '#00CC96', '#AB63FA',
    '#FFA15A', '#19D3F3', '#FF6692', '#B6E880', '#FF97FF', '#FECB52',
    '#636EFA', '#EF553B', '#636EFA', '#EF553B', '#00CC96', '#AB63FA',
    '#FFA15A', '#19D3F3', '#FF6692', '#B6E880',
]


AFRICA = [
    'Algeria',
    'Angola',
    'Benin',
    'Botswana',
    'Burkina_Faso',
    'Burundi',
    'Cameroon',
    'Canada',
    'Cape_Verde',
    'Central_African_Republic',
    'Chad',
    'Congo',
    'Cote_dIvoire',
    'Democratic_Republic_of_the_Congo',
    'Djibouti',
    'Egypt',
    'Equatorial_Guinea',
    'Eritrea',
    'Eswatini',
    'Ethiopia',
    'Gabon',
    'Gambia',
    'Ghana',
    'Guinea',
    'Guinea_Bissau',
    'Kenya',
    'Liberia',
    'Libya',
    'Madagascar',
    'Malawi',
    'Mali',
    'Mauritania',
    'Mauritius',
    'Morocco',
    'Mozambique',
    'Namibia',
    'Niger',
    'Nigeria',
    'Rwanda',
    'Senegal',
    'Seychelles',
    'Sierra_Leone',
    'Somalia',
    'South_Africa',
    'South_Sudan',
    'Sudan',
    'Togo',
    'Tunisia',
    'Uganda',
    'United_Republic_of_Tanzania',
    'Zambia',
    'Zimbabwe',
]

AMERICAS = [
    'Anguilla',
    'Antigua_and_Barbuda',
    'Argentina',
    'Aruba',
    'Bahamas',
    'Barbados',
    'Belize',
    'Bermuda',
    'Bolivia',
    'Bonaire, Saint Eustatius and Saba',
    'Brazil',
    'British_Virgin_Islands',
    'Canada',
    'Cayman_Islands',
    'Chile',
    'Colombia',
    'Costa_Rica',
    'Cuba',
    'Curaçao',
    'Dominica',
    'Dominican_Republic',
    'Ecuador',
    'El_Salvador',
    'Falkland_Islands_(Malvinas)',
    'Greenland',
    'Grenada',
    'Guatemala',
    'Guyana',
    'Haiti',
    'Honduras',
    'Jamaica',
    'Maldives',
    'Mexico',
    'Montserrat',
    'Nicaragua',
    'Panama',
    'Paraguay',
    'Peru',
    'Puerto_Rico',
    'Saint_Barthelemy',
    'Saint_Kitts_and_Nevis',
    'Saint_Lucia',
    'Saint_Vincent_and_the_Grenadines',
    'Sint_Maarten',
    'Suriname',
    'Trinidad_and_Tobago',
    'Turks_and_Caicos_islands',
    'USA',
    'United_States_Virgin_Islands',
    'Uruguay',
    'Venezuela',
]

ASIA = [
    'Afghanistan',
    'Algeria',
    'Armenia',
    'Azerbaijan',
    'Bahrain',
    'Bangladesh',
    'Bhutan',
    'Brunei_Darussalam',
    'Cambodia',
    'China',
    'Fiji',
    'French_Polynesia',
    'Guam',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Israel',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Lebanon',
    'Malaysia',
    'Mongolia',
    'Myanmar',
    'Nepal',
    'Oman',
    'Pakistan',
    'Palestine',
    'Philippines',
    'Qatar',
    'Russia',
    'Sao_Tome_and_PrincipeCases_on_an_international_conveyance_Japan',
    'Saudi_Arabia',
    'Singapore',
    'South_Korea',
    'Sri_Lanka',
    'Syria',
    'Taiwan',
    'Thailand',
    'Timor_Leste',
    'Tunisia',
    'Turkey',
    'United_Arab_Emirates',
    'Uzbekistan',
    'Vietnam',
    'Yemen',
]

EUROPE = [
    'Albania',
    'Andorra',
    'Austria',
    'Belarus',
    'Belgium',
    'Bosnia_and_Herzegovina',
    'Bulgaria',
    'Croatia',
    'Cyprus',
    'Czech_Republic',
    'Czechia',
    'Denmark',
    'Estonia',
    'Faroe_Islands',
    'Finland',
    'France',
    'Georgia',
    'Germany',
    'Gibraltar',
    'Greece',
    'Guernsey',
    'Holy_See',
    'Hungary',
    'Iceland',
    'Ireland',
    'Isle_of_Man',
    'Italy',
    'Jersey',
    'Kosovo',
    'Latvia',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Malta',
    'Moldova',
    'Monaco',
    'Montenegro',
    'Netherlands',
    'North_Macedonia',
    'Norway',
    'Poland',
    'Portugal',
    'Romania',
    'Russia',
    'San_Marino',
    'Serbia',
    'Slovakia',
    'Slovenia',
    'Spain',
    'Sweden',
    'Switzerland',
    'UK',
    'Ukraine',
]

OCEANIA = [
    'Australia',
    'New_Caledonia',
    'New_Zealand',
    'Northern_Mariana_Islands',
    'Papua_New_Guinea',
]

#=============================================================================#
#                                                                             #
#                           Elements - Spain                                  #
#                                                                             #
#=============================================================================#

COLOURS_SPAIN = [
    '#636EFA',
    '#EF553B',
    '#00CC96',
    '#AB63FA',
    '#FFA15A',
    '#19D3F3',
    '#FF6692',
    '#B6E880',
    '#FF97FF',
    '#FECB52',
    '#636EFA',
    '#EF553B',
    '#00CC96',
    '#AB63FA',
    '#FFA15A',
    '#19D3F3',
    '#FF6692',
    #'#B6E880',
    #'#FF97FF',
]

SPAIN_GEOLOCATIONS = {
    'region' :
    [
        'AN',
        'AR',
        'AS',
        'IB',
        'PV',
        'CN',
        'CB',
        'CL',
        'CM',
        'CT',
        'EX',
        'GA',
        'RI',
        'MD',
        'MC',
        'NC',
        'VC',
    ],

    'region_name' :
    [
        'Andalusia',
        'Aragon',
        'Asturias',
        'Balearic Islands',
        'Basque Country',
        'Canary Islands',
        'Cantabria',
        'Castille and Leon',
        'Castille-La Mancha',
        'Catalonia',
        'Extremadura',
        'Galicia',
        'La Rioja',
        'Madrid',
        'Murcia',
        'Navarre',
        'Valencia',
    ],

    'long' :
    [
        -4.5,
        -1.0,
        -6.0,
        2.4334717,
        -2.75,
        -15.5,
        -4.0,
        -4.25,
        -3.0,
        1.8676758,
        -6.0,
        -7.8662109,
        -2.5,
        -3.6906338,
        -1.5,
        -1.6666667,
        -0.75,
    ],

    'lat' :
    [
        37.6,
        41.0,
        43.3333333,
        39.2226789,
        43.0,
        28.0,
        43.3333333,
        41.6666667,
        39.5,
        41.8204551,
        39.0,
        42.7550796,
        42.25,
        40.4252581,
        38.0,
        42.75,
        39.5,
    ],
}
